### ISSUE TITLE
请问能否添加AArch64架构的支持

### ISSUE THREAD

**Issue by zenzen52000** [ayasa520/redroid-script#1]
请问能否添加AArch64架构的支持

**Comment by ayasa520** [comment]
你是指 magisk 安装吗? https://github.com/ayasa520/redroid-script/blob/a7d9737c4a18c88297af415708e54f14c855c5ce/tools/helper.py#L47-L65 支持的啊

**Comment by zenzen52000** [comment]
> 你是指magisk安装吗？
> 
> https://github.com/ayasa520/redroid-script/blob/a7d9737c4a18c88297af415708e54f14c855c5ce/tools/helper.py#L47-L65
> 
> 支持的啊

非常感谢 已经安装成功

**Comment by ilaipi** [comment]
我又试了试，好像使用 `python redroid.py -a 12.0.0 -m`，构建出 `12.0.0-magisk` 镜像后，直接启动，本来就是安装好的。只不过需要初始化，点了初始化之后，`docker restart phone1` 再进入手机，显示是已经安装好的，可能不需要再安装了

![image](https://github.com/ayasa520/redroid-script/assets/1689135/013632b5-8109-4873-929e-91bab372ae50)
