### ISSUE TITLE
magisk install Module Zygisk - LSPosed, but Zygisk No

### ISSUE THREAD

**Issue by vanxv** [ayasa520/redroid-script#10]
magisk install Module: Zygisk - LSPosed, but Zygisk No

erro:Module suspended because Zygisk is not enabled

* hard: rk3588 arm64
* android: 11.0.0
* docker shell :
```shell
docker run -itd --rm --privileged \
    -v ~/data_11_magisk_8558:/data \
    -p 8558:5555 \
    redroid/redroid:11.0.0_magisk
```

**Comment by ayasa520** [comment]
1. Check if Magisk is working. 
![image](https://user-images.githubusercontent.com/55699692/230722722-628072bb-bc5d-448b-b5d7-909761141449.png)

2. You need to enble zygisk manually
![image](https://user-images.githubusercontent.com/55699692/230722754-0837bd0f-a5ab-4d83-9716-a77b65ab8945.png)

**Comment by vanxv** [comment]
thank you. 
it working.

**Comment by honchy** [comment]
> magisk install Module: Zygisk - LSPosed, but Zygisk No
> 
> erro:Module suspended because Zygisk is not enabled
> 
> * hard: rk3588 arm64
> * android: 11.0.0
> * docker shell :
> 
> ```shell
> docker run -itd --rm --privileged \
>     -v ~/data_11_magisk_8558:/data \
>     -p 8558:5555 \
>     redroid/redroid:11.0.0_magisk
> ```

@ayasa520  Is the --privileged flag necessary to include in the command line?
