### ISSUE TITLE
Can't install latest Magisk Delta .

### ISSUE THREAD

**Issue by gyhmz** [ayasa520/redroid-script#19]
不知道什么原因最新版magisk delta 不能用，显示未安装，把 stuffs/magisk.py里dl_link换成旧版就能用了

**Comment by maomaochong199** [comment]
旧版链接是多少

**Comment by 940842546** [comment]
> 旧版链接是多少

https://github.com/HuskyDG/magisk-files/raw/X/v26.1-delta.apk

**Comment by 940842546** [comment]
> 旧版链接是多少

https://github.com/HuskyDG/magisk-files/releases/download/fdac22ba-delta/app-release.apk

**Comment by Bleach665** [comment]
> > 旧版链接是多少
> 
> https://github.com/HuskyDG/magisk-files/releases/download/fdac22ba-delta/app-release.apk

@940842546  This file not exist yet. Can you please give a mirror or share this file here?

**Comment by ayasa520** [comment]
是这样，因为新的 magisk delta（现在叫 Kitsune）不再支持 selinux deisabled 设备。不过旧版的可以继续使用，现在 redroid-script 提供的是 25210 的版本
