### ISSUE TITLE
OpenGapps md5 mismatches

### ISSUE THREAD

**Issue by ysy950803** [ayasa520/redroid-script#20]
python redroid.py -a 12.0.0_64only -gm

```
Downloading OpenGapps now .....
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 76.7kiB/s]
md5 mismatches, redownloading now ....
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 91.9kiB/s]
md5 mismatches, redownloading now ....
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 146/146 [00:00<00:00, 100kiB/s]
md5 mismatches, redownloading now ....
```

You can see that cannot be downloaded.

**Comment by ctaoist** [comment]
脚本的 gapp 的下载链接是 `https://master.dl.sourceforge.net/project/opengapps/x86_64/20220121/open_gapps-x86_64-10.0-pico-20220121.zip?viasf=1`,但这个链接目前不存在了，作者更新一下吧，我改成 20220503 版本，又提示这个错误：`No such file or directory /tmp/ogapps/extract/appunpack/vending-common/nodpi`
@ayasa520

**Comment by ysy950803** [comment]
修复失效链接：https://github.com/ayasa520/redroid-script/pull/22

**Comment by ysy950803** [comment]
> 脚本的 gapp 的下载链接是 `https://master.dl.sourceforge.net/project/opengapps/x86_64/20220121/open_gapps-x86_64-10.0-pico-20220121.zip?viasf=1`,但这个链接目前不存在了，作者更新一下吧，我改成 20220503 版本，又提示这个错误：`No such file or directory /tmp/ogapps/extract/appunpack/vending-common/nodpi` @ayasa520

我修复链接后没问题了，中间也遇到过你说的No such file的问题，是Python的问题，必须保证环境是Python 3.8及以上，pip也要安装pip3.8及以上。解压工具的话保证tar和lzip两个命令可用。

**Comment by vuongtuha** [comment]
Did anyone find a way to fix it?
I changed open gapps link in stuffs/gapps.py to "https://master.dl.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip?viasf=1" "5a6d242be34ad1acf92899c7732afa1b"
Download is fine but then a wall of text traceback error
  File "/home/phuogmai/Programs/redroid-script/redroid.py", line 79, in <module>
    main()
  File "/home/phuogmai/Programs/redroid-script/redroid.py", line 48, in main
    Gapps().install()
  File "/home/phuogmai/Programs/redroid-script/stuffs/general.py", line 34, in install
    self.copy()
  File "/home/phuogmai/Programs/redroid-script/stuffs/gapps.py", line 51, in copy
Any other temp solution?

**Comment by ZZZ-zero** [comment]
> Did anyone find a way to fix it? I changed open gapps link in stuffs/gapps.py to "https://master.dl.sourceforge.net/project/opengapps/x86_64/20220503/open_gapps-x86_64-11.0-pico-20220503.zip?viasf=1" "5a6d242be34ad1acf92899c7732afa1b" Download is fine but then a wall of text traceback error File "/home/phuogmai/Programs/redroid-script/redroid.py", line 79, in main() File "/home/phuogmai/Programs/redroid-script/redroid.py", line 48, in main Gapps().install() File "/home/phuogmai/Programs/redroid-script/stuffs/general.py", line 34, in install self.copy() File "/home/phuogmai/Programs/redroid-script/stuffs/gapps.py", line 51, in copy Any other temp solution?

在 stuffs/gapps.py的non_apks处添加："vending-common.tar.lz",
即可，参考https://github.com/casualsnek/waydroid_script/issues/30#issuecomment-1099397952
